### ISSUE TITLE
Object History year defaults to 2019 

### ISSUE THREAD

**Issue by mainnebula** [TruSat/trusat-frontend#291]
Within an individual object's history, the default year of observations is set to 2019 when it should be 2020. 

[Can be seen in the history of this object. ](https://trusat.org/object/25771)

**Comment by johngribbin** [comment]
Good spot @mainnebula 

Peep the component here - https://github.com/TruSat/trusat-frontend/blob/dev/src/objects/components/HistoryYearDropdown.js

And see if you can work out a quick fix!

See tips for contributing on the README here - https://github.com/TruSat/trusat-frontend/blob/master/README.md
