### ISSUE TITLE
Observers are unable to add an 11th station to their account

### ISSUE THREAD

**Issue by mikeville** [TruSat/trusat-frontend#294]
Brad experienced this on Chrome and Firefox, and I was able to reproduce. When I try filling out the station form to add an 11th station, and click the button to submit, I'm taken to a blank screen. When I return to my settings page, the new station is not displayed in my station list.

**Comment by johngribbin** [comment]
@Kmoneal 

Perhaps we can consider lifting the cap to 20 stations?

**Comment by interplanetarychris** [comment]
So this is a reminder that for implementation ease, we set a hard cap at 10 stations.

Is there a way to remove a limit?

**Comment by johngribbin** [comment]
@interplanetarychris Kenan just lifted the limit

**Comment by Kmoneal** [comment]
If I remember right, it was to reduce clutter

**Comment by johngribbin** [comment]
Change here - https://github.com/TruSat/trusat-backend/blob/ff747c4a38f7fcf10d5ed11dfbce0082c80a4d6a/database.py#L4026
